# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^tests/data/
      - id: mixed-line-ending
        exclude: ^tests/data/
      - id: name-tests-test
      - id: trailing-whitespace
        exclude: ^tests/data/

  - repo: https://github.com/ninoseki/uv-sort
    rev: v0.7.0
    hooks:
      - id: uv-sort

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
      - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: pyfltr
        name: pyfltr
        entry: uv run pyfltr --exit-zero-even-if-formatted --commands=fast
        types: [python]
        pass_filenames: false
        require_serial: true
        language: system
      - id: textlint
        name: textlint
        entry: textlint
        language: node
        files: \.(md|mdown|markdown)$
        args: []
        require_serial: false
        additional_dependencies:
          - textlint@15.5.1
          - textlint-rule-preset-ja-technical-writing@12.0.2
          - textlint-rule-preset-japanese@10.0.4
